name = "maenun-champion"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAyE0gdR5wdyXzKCwUV-c5C_1VxdrF6j08"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "maenun-champion.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "maenun-champion"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "maenun-champion.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "957245499146"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:957245499146:web:29b6c8b6946a585733fcf3"
